// Generated by Loveable Web Architect — DO NOT EDIT MANUALLY
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { FileText, Download, Calendar } from "lucide-react";
import Navigation from "@/components/Navigation";

// This would typically be loaded from data/docs.json in a real Next.js app
const documents = [
  { 
    file: "Surat-Kemenkumham-PTMMI.pdf", 
    title: "SK Pengesahan Kemenkumham", 
    date: "2025-07-22",
    category: "Legal"
  },
  { 
    file: "Company-Profile-PTMMI.pdf", 
    title: "Company Profile PT MMI", 
    date: "2024-11-15",
    category: "Corporate"
  },
  { 
    file: "Business-License-PTMMI.pdf", 
    title: "Izin Usaha Perdagangan", 
    date: "2022-11-04",
    category: "License"
  },
  { 
    file: "Financial-Report-2023.pdf", 
    title: "Laporan Keuangan 2023", 
    date: "2024-03-31",
    category: "Financial"
  }
];

const Documents = () => {
  return (
    <div className="min-h-screen bg-gradient-to-b from-background to-muted">
      <Navigation />
      {/* Hero Section */}
      <section className="py-20 bg-primary text-primary-foreground" data-lovable-tag="documents-hero">
        <div className="container mx-auto px-6">
          <div className="text-center max-w-4xl mx-auto">
            <FileText className="w-16 h-16 mx-auto mb-6 text-accent" />
            <h1 className="text-4xl md:text-6xl font-bold mb-6">
              Corporate Documents
            </h1>
            <p className="text-xl md:text-2xl text-primary-foreground/90 leading-relaxed">
              Access our complete collection of legal documents, certifications, and corporate reports. 
              Transparency and compliance are the foundations of trust.
            </p>
          </div>
        </div>
      </section>

      {/* Documents List */}
      <section className="py-20" data-lovable-tag="documents-list">
        <div className="container mx-auto px-6">
          <div className="max-w-6xl mx-auto">
            <h2 className="text-3xl md:text-4xl font-bold text-center mb-16 text-primary">
              Official Documentation
            </h2>
            
            <div className="grid lg:grid-cols-2 gap-8">
              {documents.map((doc, index) => (
                <Card key={index} className="shadow-card hover:shadow-xl transition-all duration-300 border-0 bg-gradient-to-b from-card to-muted/20">
                  <CardHeader className="pb-4">
                    <div className="flex items-start justify-between mb-4">
                      <div className="flex items-center gap-3">
                        <FileText className="w-8 h-8 text-accent" />
                        <div>
                          <CardTitle className="text-xl text-primary mb-2">
                            {doc.title}
                          </CardTitle>
                          <div className="flex items-center gap-3">
                            <Badge variant="outline" className="bg-accent/10 text-accent border-accent/20">
                              {doc.category}
                            </Badge>
                            <div className="flex items-center gap-1 text-muted-foreground text-sm">
                              <Calendar className="w-4 h-4" />
                              {new Date(doc.date).toLocaleDateString('id-ID', {
                                year: 'numeric',
                                month: 'long',
                                day: 'numeric'
                              })}
                            </div>
                          </div>
                        </div>
                      </div>
                      <Button variant="outline" size="sm">
                        <Download className="w-4 h-4 mr-2" />
                        Download
                      </Button>
                    </div>
                  </CardHeader>
                  
                  <CardContent>
                    <div className="bg-muted/50 rounded-lg p-4">
                      <p className="text-sm text-muted-foreground mb-4">
                        Document Preview:
                      </p>
                      
                      {/* PDF Preview - In a real app, this would show actual PDF */}
                      <div className="bg-white rounded border-2 border-dashed border-border h-48 flex items-center justify-center">
                        <div className="text-center">
                          <FileText className="w-12 h-12 mx-auto mb-2 text-muted-foreground" />
                          <p className="text-sm text-muted-foreground">
                            PDF Preview
                          </p>
                          <p className="text-xs text-muted-foreground/70">
                            {doc.file}
                          </p>
                        </div>
                      </div>
                      
                      {/* In a real Next.js app with getStaticProps, this would be:
                      <iframe 
                        src={`/docs/${doc.file}`}
                        className="w-full h-48 rounded border"
                        title={doc.title}
                      />
                      */}
                    </div>
                    
                    <div className="mt-4 pt-4 border-t border-border">
                      <p className="text-sm text-muted-foreground">
                        This document is available for download and review. All documents are 
                        kept up-to-date and reflect our current legal and operational status.
                      </p>
                    </div>
                  </CardContent>
                </Card>
              ))}
            </div>
            
            <div className="text-center mt-12">
              <p className="text-lg text-muted-foreground mb-6">
                Need additional documentation or have questions about our corporate structure?
              </p>
              <Button variant="industrial" size="lg">
                Contact Our Legal Team
              </Button>
            </div>
          </div>
        </div>
      </section>
    </div>
  );
};

export default Documents;