// Generated by Loveable Web Architect — DO NOT EDIT MANUALLY
import { Button } from "@/components/ui/button";
import Navigation from "./Navigation";
import heroImage from "@/assets/hero-industrial.jpg";
import { Link } from "react-router-dom";

const HeroSection = () => {
  return (
    <section className="relative min-h-screen flex items-center justify-center overflow-hidden" data-lovable-tag="hero-section">
      <Navigation />
      {/* Background Image with Overlay */}
      <div className="absolute inset-0 z-0">
        <img 
          src={heroImage} 
          alt="Industrial landscape" 
          className="w-full h-full object-cover"
        />
        <div className="absolute inset-0 bg-gradient-to-r from-primary/90 via-primary/70 to-primary/50"></div>
      </div>
      
      {/* Content */}
      <div className="relative z-10 container mx-auto px-6 text-center text-white">
        <h1 className="text-5xl md:text-7xl font-bold mb-8 leading-tight">
          Building Indonesia's
          <span className="block text-accent">Industrial Future</span>
        </h1>
        
        <p className="text-xl md:text-2xl mb-12 max-w-4xl mx-auto leading-relaxed opacity-95">
          From the heart of Sulawesi Tenggara, we connect industries with essential materials. 
          Since 2022, PT Multi Mineral Indotama has been the trusted bridge between suppliers 
          and builders, fueling Indonesia's growth one partnership at a time.
        </p>
        
        <div className="flex flex-col sm:flex-row gap-6 justify-center">
          <Button variant="hero" size="lg" className="text-lg px-8 py-4">
            Partner With Us
          </Button>
          <Link to="/documents">
            <Button variant="outline" size="lg" className="text-lg px-8 py-4 bg-white/10 border-white/30 text-white hover:bg-white/20">
              View Documents
            </Button>
          </Link>
        </div>
      </div>
      
      {/* Scroll Indicator */}
      <div className="absolute bottom-8 left-1/2 transform -translate-x-1/2 animate-bounce">
        <div className="w-6 h-10 border-2 border-white/50 rounded-full flex justify-center">
          <div className="w-1 h-3 bg-white/70 rounded-full mt-2"></div>
        </div>
      </div>
    </section>
  );
};

export default HeroSection;