// Generated by Loveable Web Architect — DO NOT EDIT MANUALLY
import { Button } from "@/components/ui/button";
import { FileText, Home } from "lucide-react";
import { Link, useLocation } from "react-router-dom";

const Navigation = () => {
  const location = useLocation();
  
  return (
    <nav className="fixed top-6 left-1/2 transform -translate-x-1/2 z-50 bg-white/10 backdrop-blur-md border border-white/20 rounded-full px-6 py-3" data-lovable-tag="navigation">
      <div className="flex items-center gap-4">
        <Link to="/">
          <Button 
            variant={location.pathname === "/" ? "hero" : "ghost"} 
            size="sm"
            className={location.pathname === "/" ? "" : "text-white hover:bg-white/20"}
          >
            <Home className="w-4 h-4 mr-2" />
            Home
          </Button>
        </Link>
        
        <Link to="/documents">
          <Button 
            variant={location.pathname === "/documents" ? "hero" : "ghost"} 
            size="sm"
            className={location.pathname === "/documents" ? "" : "text-white hover:bg-white/20"}
          >
            <FileText className="w-4 h-4 mr-2" />
            Documents
          </Button>
        </Link>
      </div>
    </nav>
  );
};

export default Navigation;